# Generated by Django 2.2.1 on 2020-10-09 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('points', models.TextField()),
                ('status', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=10)),
                ('profile', models.CharField(default='http://res.cloudinary.com/dqaiapvgm/image/upload/v1602228372/profile_picture_swxnoc.webp', max_length=250)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('shared_to', models.ManyToManyField(blank=True, related_name='shared_to_me', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
